services:
  minecraft:
    container_name: minecraft-server
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      ONLINE_MODE: "TRUE"
    volumes:
      - ./minecraft/data:/data
    restart: unless-stopped
